version: '3.5'

services:
  multipart-server:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        - node_environment=${ENVIRONMENT}
        - upload_dir=${UPLOAD_DIR}
    # platform: linux/amd64
    image: andrat/multipart-${APP_NAME}
    container_name: andrat-multipart-${APP_NAME}
    env_file:
      - ./app/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app
    ports:
      - 8083:${APP_PORT}
    command: >
      sh -c "yarn start:dev"
