version: '3.5'

services:
  uploader:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        - upload_dir=${UPLOAD_DIR}
#    platform: linux/amd64
    image: effiware/multipart-artic-${APP_NAME}
    container_name: effi-artic-multipart-${APP_NAME}
    env_file:
      - ./app/.env
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
#      - ./app/logs:/app/logs
    ports:
      - "30084:80"
    # mem_limit: 300m
    # oom_kill_disable: true
#    command: >
#      sh -c "python main.py"