apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: monitoring
  labels:
    type: local
    app: prometheus-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
