version: '3.5'

services:
  uploader:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        - upload_dir=${UPLOAD_DIR}
#    platform: linux/amd64
    image: andrat/multipart-${APP_NAME}
    container_name: andrat-multipart-${APP_NAME}
    env_file:
      - ./app/.env
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    #   - ./app/logs:/app/logs
    ports:
      - "30085:80"
    # mem_limit: 300m
    # oom_kill_disable: true
    command: >
      sh -c "python app.py"