version: '3.5'

services:
  multipart-server:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      args:
        - node_environment=${ENVIRONMENT}
        - upload_dir=${UPLOAD_DIR}
    # platform: linux/amd64
    image: effiware/artic-multipart-${APP_NAME}
    container_name: effi-artic-multipart-${APP_NAME}
    env_file:
      - ./app/.env
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    #   - ./app:/app
    ports:
      - 30081:${APP_PORT}
    # mem_limit: 300m
    # oom_kill_disable: true
    command: >
      sh -c "yarn start:dev"cd